apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qqnj12m5z-java-springboot 
  janus-idp.io/tekton: qqnj12m5z-java-springboot
  backstage.io/kubernetes-id: qqnj12m5z-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qqnj12m5z-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml